name = "camera-streaming-app"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "camera-streaming-app-prod"

# Durable Objects for WebSocket handling
[[durable_objects.bindings]]
name = "WEBSOCKET_HANDLER"
class_name = "WebSocketHandler"

# KV for storing metadata (optional)
[[kv_namespaces]]
binding = "CAMERA_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# R2 for file storage
[[r2_buckets]]
binding = "CAMERA_STORAGE"
bucket_name = "camera-uploads"